# Generated by Django 3.2.6 on 2021-08-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price_course_string',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Цена пропьсью'),
        ),
    ]
