# Generated by Django 3.2.6 on 2021-08-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_price_course_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='price_course_string',
        ),
    ]
